name: Build Multi-Platform

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: npm run build

      - name: Build Electron app (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: npm run package-linux

      - name: Build Electron app (Windows)
        if: matrix.os == 'windows-latest'
        run: npm run package-win

      - name: Build Electron app (macOS)
        if: matrix.os == 'macos-latest'
        run: npm run package-mac

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: release/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
